package tetour.com.enums;

import lombok.Getter;
import lombok.Setter;
import org.springframework.http.HttpStatus;
import tetour.com.contants.IMessages;

@Getter
public enum ErrorCode {
    USER_BANNED(IMessages.USER_BANNED, HttpStatus.FORBIDDEN),
    USER_NOT_FOUND(IMessages.USER_NOT_FOUND, HttpStatus.NOT_FOUND),
    USERNAME_OR_EMAIL_ALREADY_EXISTS(IMessages.USERNAME_OR_EMAIL_ALREADY_EXISTS, HttpStatus.CONFLICT),
    USERNAME_ALREADY_EXISTS(IMessages.USERNAME_ALREADY_EXISTS, HttpStatus.BAD_REQUEST),
    EMAIL_ALREADY_EXISTS(IMessages.EMAIL_ALREADY_EXISTS, HttpStatus.BAD_REQUEST),
    INVALID_CREDENTIALS(IMessages.INVALID_CREDENTIALS, HttpStatus.UNAUTHORIZED),
    INVALID_REFRESH_TOKEN(IMessages.INVALID_REFRESH_TOKEN, HttpStatus.UNAUTHORIZED),
    INVALID_PASSWORD(IMessages.INVALID_PASSWORD, HttpStatus.BAD_REQUEST),
    LENGTH_PASSWORD(IMessages.LENGTH_PASSWORD, HttpStatus.BAD_REQUEST),
    INVALID_USERNAME(IMessages.INVALID_USERNAME, HttpStatus.BAD_REQUEST),
    INVALID_EMAIL(IMessages.INVALID_EMAIL, HttpStatus.BAD_REQUEST),
    PERMISSION_NOT_FOUND(IMessages.PERMISSION_NOT_FOUND, HttpStatus.NOT_FOUND),
    UNKNOWN_ERROR(IMessages.UNKNOWN_ERROR, HttpStatus.INTERNAL_SERVER_ERROR),
    UNAUTHORIZED(IMessages.UNAUTHORIZED, HttpStatus.UNAUTHORIZED),
    UNAUTHENTICATED(IMessages.UNAUTHENTICATED, HttpStatus.FORBIDDEN),
    FORBIDDEN(IMessages.FORBIDDEN, HttpStatus.FORBIDDEN),
    INVALID_TOKEN(IMessages.INVALID_TOKEN, HttpStatus.UNAUTHORIZED),
    SEND_MAIL_FAILED(IMessages.SEND_MAIL_FAILED, HttpStatus.INTERNAL_SERVER_ERROR),
    ROLE_NOT_FOUND(IMessages.ROLE_NOT_FOUND, HttpStatus.BAD_REQUEST),
    SUBJECT_NOT_FOUND(IMessages.SUBJECT_NOT_FOUND, HttpStatus.NOT_FOUND),
    SUBJECT_CODE_ALREADY_EXISTS(IMessages.SUBJECT_CODE_ALREADY_EXISTS, HttpStatus.BAD_REQUEST),
    CLASS_NOT_FOUND(IMessages.CLASS_NOT_FOUND, HttpStatus.NOT_FOUND),
    CLASS_CODE_NOT_FOUND(IMessages.CLASS_CODE_NOT_FOUND, HttpStatus.NOT_FOUND),
    TEACHER_NOT_FOUND(IMessages.TEACHER_NOT_FOUND, HttpStatus.NOT_FOUND),
    TEACHER_ALREADY_EXISTS(IMessages.TEACHER_ALREADY_EXISTS, HttpStatus.BAD_REQUEST),
    CLASS_SUBJECT_NOT_FOUND(IMessages.CLASS_SUBJECT_NOT_FOUND, HttpStatus.NOT_FOUND),
    CLASS_SUBJECT_ALREADY_EXISTS(IMessages.CLASS_SUBJECT_ALREADY_EXISTS, HttpStatus.BAD_REQUEST),
    CLASS_TEACHER_NOT_FOUND(IMessages.CLASS_TEACHER_NOT_FOUND, HttpStatus.NOT_FOUND),
    CLASS_TEACHER_ALREADY_EXISTS(IMessages.CLASS_TEACHER_ALREADY_EXISTS, HttpStatus.BAD_REQUEST),
    TIMETABLE_NOT_FOUND(IMessages.TIMETABLE_NOT_FOUND, HttpStatus.NOT_FOUND),
    TIMETABLE_OVERLAP(IMessages.TIMETABLE_OVERLAP, HttpStatus.CONFLICT),
    CLASS_STUDENT_NOT_FOUND(IMessages.CLASS_STUDENT_NOT_FOUND, HttpStatus.NOT_FOUND),
    CLASS_STUDENT_ALREADY_EXISTS(IMessages.CLASS_STUDENT_ALREADY_EXISTS, HttpStatus.BAD_REQUEST),
    STUDENT_NOT_FOUND(IMessages.STUDENT_NOT_FOUND, HttpStatus.NOT_FOUND),
    OLD_PASSWORD_NOT_MATCH(IMessages.OLDPASSWORD_NOT_MATCH, HttpStatus.BAD_REQUEST ), CONFIRM_PASSWORD_NOT_MATCH(IMessages.CONFIRM_PASSWORD_NOT_MATCH, HttpStatus.BAD_REQUEST );

    private final String message;
    private final HttpStatus httpStatus;

    ErrorCode(String message, HttpStatus httpStatus) {
        this.message = message;
        this.httpStatus = httpStatus;
    }
}
