import type { Metadata } from 'next';
import React from 'react';
import './globals.css';
import { ReactQueryProvider } from 'src/shared/providers/ReactQueryProvider';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
